const sampleListings = [
  {
    title: "iPhone 13 Pro",
    description: "128GB, excellent condition, no scratches.",
    image: "https://images.unsplash.com/photo-1632661674596-df8be070a5c5",
    price: 65000,
    location: "Kolkata",
    country: "India",
    category: "Mobile",
    condition: "Used",
    exchangeWith: "Samsung S22",
  },
  {
    title: "Samsung Galaxy S22",
    description: "Flagship Android phone, smooth performance.",
    image: "https://images.unsplash.com/photo-1644508762263-4b7e7c77c4c6",
    price: 52000,
    location: "Delhi",
    country: "India",
    category: "Mobile",
    condition: "Used",
    exchangeWith: "iPhone 12",
  },
  {
    title: "OnePlus 11",
    description: "Fast and smooth, 5G supported.",
    image: "https://images.unsplash.com/photo-1610792516307-ea5acd9c3b00",
    price: 48000,
    location: "Mumbai",
    country: "India",
    category: "Mobile",
    condition: "New",
    exchangeWith: "iPhone 13",
  },
  {
    title: "MacBook Air M1",
    description: "Lightweight and powerful laptop.",
    image: "https://images.unsplash.com/photo-1603791440384-56cd371ee9a7",
    price: 75000,
    location: "Bangalore",
    country: "India",
    category: "Laptop",
    condition: "Used",
    exchangeWith: "Gaming Laptop",
  },
  {
    title: "Dell Gaming Laptop",
    description: "RTX graphics, perfect for gaming.",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
    price: 90000,
    location: "Hyderabad",
    country: "India",
    category: "Laptop",
    condition: "Used",
    exchangeWith: "MacBook",
  },
  {
    title: "HP Pavilion Laptop",
    description: "Office and study laptop.",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853",
    price: 35000,
    location: "Pune",
    country: "India",
    category: "Laptop",
    condition: "Used",
    exchangeWith: "Tablet",
  },
  {
    title: "Sony WH-1000XM4",
    description: "Noise cancelling premium headphones.",
    image: "https://images.unsplash.com/photo-1580894908361-967195033215",
    price: 18000,
    location: "Chennai",
    country: "India",
    category: "Accessories",
    condition: "Used",
    exchangeWith: "AirPods Pro",
  },
  {
    title: "AirPods Pro",
    description: "Apple wireless earbuds.",
    image: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad",
    price: 20000,
    location: "Kolkata",
    country: "India",
    category: "Accessories",
    condition: "Used",
    exchangeWith: "Sony Headphones",
  },
  {
    title: "Apple Watch Series 7",
    description: "Smartwatch with fitness tracking.",
    image: "https://images.unsplash.com/photo-1516574187841-cb9cc2ca948b",
    price: 25000,
    location: "Delhi",
    country: "India",
    category: "Accessories",
    condition: "Used",
    exchangeWith: "Galaxy Watch",
  },
  {
    title: "Samsung Galaxy Watch",
    description: "Smartwatch for Android users.",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30",
    price: 18000,
    location: "Mumbai",
    country: "India",
    category: "Accessories",
    condition: "New",
    exchangeWith: "Apple Watch",
  },
  {
    title: "iPad 9th Gen",
    description: "Perfect for students.",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3",
    price: 30000,
    location: "Bangalore",
    country: "India",
    category: "Tablet",
    condition: "Used",
    exchangeWith: "Android Tablet",
  },
  {
    title: "Samsung Tab S7",
    description: "High performance Android tablet.",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3",
    price: 35000,
    location: "Hyderabad",
    country: "India",
    category: "Tablet",
    condition: "Used",
    exchangeWith: "iPad",
  },
  {
    title: "Canon DSLR Camera",
    description: "Professional photography camera.",
    image: "https://images.unsplash.com/photo-1519183071298-a2962eadc6b5",
    price: 50000,
    location: "Jaipur",
    country: "India",
    category: "Camera",
    condition: "Used",
    exchangeWith: "Mirrorless Camera",
  },
  {
    title: "Sony Mirrorless Camera",
    description: "Compact and powerful camera.",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32",
    price: 60000,
    location: "Goa",
    country: "India",
    category: "Camera",
    condition: "Used",
    exchangeWith: "DSLR",
  },
  {
    title: "PlayStation 5",
    description: "Next-gen gaming console.",
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db",
    price: 55000,
    location: "Kolkata",
    country: "India",
    category: "Gaming",
    condition: "New",
    exchangeWith: "Xbox Series X",
  },
  {
    title: "Xbox Series X",
    description: "Powerful gaming console.",
    image: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d",
    price: 52000,
    location: "Delhi",
    country: "India",
    category: "Gaming",
    condition: "New",
    exchangeWith: "PS5",
  },
  {
    title: "LG 4K Smart TV",
    description: "Ultra HD smart TV.",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1",
    price: 45000,
    location: "Mumbai",
    country: "India",
    category: "Electronics",
    condition: "New",
    exchangeWith: "Laptop",
  },
  {
    title: "Boat Bluetooth Speaker",
    description: "Portable speaker.",
    image: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad",
    price: 5000,
    location: "Chennai",
    country: "India",
    category: "Accessories",
    condition: "New",
    exchangeWith: "Headphones",
  },
  {
    title: "Gaming Keyboard",
    description: "RGB mechanical keyboard.",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8",
    price: 4000,
    location: "Pune",
    country: "India",
    category: "Accessories",
    condition: "New",
    exchangeWith: "Mouse",
  },
  {
    title: "Gaming Mouse",
    description: "High precision RGB mouse.",
    image: "https://images.unsplash.com/photo-1587202372775-989f9f28c2d6",
    price: 1500,
    location: "Bangalore",
    country: "India",
    category: "Accessories",
    condition: "New",
    exchangeWith: "Keyboard",
  },
];

module.exports = { data: sampleListings };
